// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file campus/v1/common.proto (package campus.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file campus/v1/common.proto.
 */
export const file_campus_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChZjYW1wdXMvdjEvY29tbW9uLnByb3RvEgljYW1wdXMudjEiRQoLUmVxdWVzdE1ldGESEgoKcmVxdWVzdF9pZBgBIAEoCRIQCghhY3Rvcl9pZBgCIAEoCRIQCgh0eF90b2tlbhgDIAEoCSI9Cg5CZWdpblR4UmVxdWVzdBISCgpyZXF1ZXN0X2lkGAEgASgJEhcKD3RpbWVvdXRfc2Vjb25kcxgCIAEoBSI8Cg9CZWdpblR4UmVzcG9uc2USEAoIdHhfdG9rZW4YASABKAkSFwoPZXhwaXJlc19hdF91bml4GAIgASgDIiMKD0NvbW1pdFR4UmVxdWVzdBIQCgh0eF90b2tlbhgBIAEoCSIjChBDb21taXRUeFJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgiJQoRUm9sbGJhY2tUeFJlcXVlc3QSEAoIdHhfdG9rZW4YASABKAkiJQoSUm9sbGJhY2tUeFJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgy4wEKD0RhdGFiYXNlU2VydmljZRJACgdCZWdpblR4EhkuY2FtcHVzLnYxLkJlZ2luVHhSZXF1ZXN0GhouY2FtcHVzLnYxLkJlZ2luVHhSZXNwb25zZRJDCghDb21taXRUeBIaLmNhbXB1cy52MS5Db21taXRUeFJlcXVlc3QaGy5jYW1wdXMudjEuQ29tbWl0VHhSZXNwb25zZRJJCgpSb2xsYmFja1R4EhwuY2FtcHVzLnYxLlJvbGxiYWNrVHhSZXF1ZXN0Gh0uY2FtcHVzLnYxLlJvbGxiYWNrVHhSZXNwb25zZUJTWlFnaXRodWIuY29tL1lvZ2VzaC1LdW1hci1NYWxsaWstZGV2L2NhbXB1cy1vcy9iYWNrZW5kL3BrZy9wcm90by9jYW1wdXMvdjE7Y2FtcHVzdjFiBnByb3RvMw");

/**
 * Request metadata containing transaction lease token and correlation context
 *
 * @generated from message campus.v1.RequestMeta
 */
export type RequestMeta = Message<"campus.v1.RequestMeta"> & {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * @generated from field: string actor_id = 2;
   */
  actorId: string;

  /**
   * @generated from field: string tx_token = 3;
   */
  txToken: string;
};

/**
 * Describes the message campus.v1.RequestMeta.
 * Use `create(RequestMetaSchema)` to create a new message.
 */
export const RequestMetaSchema: GenMessage<RequestMeta> = /*@__PURE__*/
  messageDesc(file_campus_v1_common, 0);

/**
 * Transaction session initiation
 *
 * @generated from message campus.v1.BeginTxRequest
 */
export type BeginTxRequest = Message<"campus.v1.BeginTxRequest"> & {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * @generated from field: int32 timeout_seconds = 2;
   */
  timeoutSeconds: number;
};

/**
 * Describes the message campus.v1.BeginTxRequest.
 * Use `create(BeginTxRequestSchema)` to create a new message.
 */
export const BeginTxRequestSchema: GenMessage<BeginTxRequest> = /*@__PURE__*/
  messageDesc(file_campus_v1_common, 1);

/**
 * @generated from message campus.v1.BeginTxResponse
 */
export type BeginTxResponse = Message<"campus.v1.BeginTxResponse"> & {
  /**
   * @generated from field: string tx_token = 1;
   */
  txToken: string;

  /**
   * @generated from field: int64 expires_at_unix = 2;
   */
  expiresAtUnix: bigint;
};

/**
 * Describes the message campus.v1.BeginTxResponse.
 * Use `create(BeginTxResponseSchema)` to create a new message.
 */
export const BeginTxResponseSchema: GenMessage<BeginTxResponse> = /*@__PURE__*/
  messageDesc(file_campus_v1_common, 2);

/**
 * @generated from message campus.v1.CommitTxRequest
 */
export type CommitTxRequest = Message<"campus.v1.CommitTxRequest"> & {
  /**
   * @generated from field: string tx_token = 1;
   */
  txToken: string;
};

/**
 * Describes the message campus.v1.CommitTxRequest.
 * Use `create(CommitTxRequestSchema)` to create a new message.
 */
export const CommitTxRequestSchema: GenMessage<CommitTxRequest> = /*@__PURE__*/
  messageDesc(file_campus_v1_common, 3);

/**
 * @generated from message campus.v1.CommitTxResponse
 */
export type CommitTxResponse = Message<"campus.v1.CommitTxResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message campus.v1.CommitTxResponse.
 * Use `create(CommitTxResponseSchema)` to create a new message.
 */
export const CommitTxResponseSchema: GenMessage<CommitTxResponse> = /*@__PURE__*/
  messageDesc(file_campus_v1_common, 4);

/**
 * @generated from message campus.v1.RollbackTxRequest
 */
export type RollbackTxRequest = Message<"campus.v1.RollbackTxRequest"> & {
  /**
   * @generated from field: string tx_token = 1;
   */
  txToken: string;
};

/**
 * Describes the message campus.v1.RollbackTxRequest.
 * Use `create(RollbackTxRequestSchema)` to create a new message.
 */
export const RollbackTxRequestSchema: GenMessage<RollbackTxRequest> = /*@__PURE__*/
  messageDesc(file_campus_v1_common, 5);

/**
 * @generated from message campus.v1.RollbackTxResponse
 */
export type RollbackTxResponse = Message<"campus.v1.RollbackTxResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message campus.v1.RollbackTxResponse.
 * Use `create(RollbackTxResponseSchema)` to create a new message.
 */
export const RollbackTxResponseSchema: GenMessage<RollbackTxResponse> = /*@__PURE__*/
  messageDesc(file_campus_v1_common, 6);

/**
 * Canonical Database Persistence Service (TypeScript DB Layer over UDS)
 *
 * @generated from service campus.v1.DatabaseService
 */
export const DatabaseService: GenService<{
  /**
   * @generated from rpc campus.v1.DatabaseService.BeginTx
   */
  beginTx: {
    methodKind: "unary";
    input: typeof BeginTxRequestSchema;
    output: typeof BeginTxResponseSchema;
  },
  /**
   * @generated from rpc campus.v1.DatabaseService.CommitTx
   */
  commitTx: {
    methodKind: "unary";
    input: typeof CommitTxRequestSchema;
    output: typeof CommitTxResponseSchema;
  },
  /**
   * @generated from rpc campus.v1.DatabaseService.RollbackTx
   */
  rollbackTx: {
    methodKind: "unary";
    input: typeof RollbackTxRequestSchema;
    output: typeof RollbackTxResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_campus_v1_common, 0);

