// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: campus/v1/auth.proto

package campusv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_BootstrapSuperAdmin_FullMethodName      = "/campus.v1.AuthService/BootstrapSuperAdmin"
	AuthService_GenerateExecutiveQR_FullMethodName      = "/campus.v1.AuthService/GenerateExecutiveQR"
	AuthService_GenerateBulkStudentQR_FullMethodName    = "/campus.v1.AuthService/GenerateBulkStudentQR"
	AuthService_ValidateClaimToken_FullMethodName       = "/campus.v1.AuthService/ValidateClaimToken"
	AuthService_VerifySIMAndSendOTP_FullMethodName      = "/campus.v1.AuthService/VerifySIMAndSendOTP"
	AuthService_VerifyOTPAndClaimAccount_FullMethodName = "/campus.v1.AuthService/VerifyOTPAndClaimAccount"
	AuthService_Login_FullMethodName                    = "/campus.v1.AuthService/Login"
	AuthService_RefreshToken_FullMethodName             = "/campus.v1.AuthService/RefreshToken"
	AuthService_RevokeSession_FullMethodName            = "/campus.v1.AuthService/RevokeSession"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Authentication and Identity Provisioning Service
type AuthServiceClient interface {
	// Genesis bootstrap for the Chairperson Super Admin seat via bare-metal CLI
	BootstrapSuperAdmin(ctx context.Context, in *BootstrapSuperAdminRequest, opts ...grpc.CallOption) (*BootstrapSuperAdminResponse, error)
	// Generates sealed credential QR codes for the Executive Council
	GenerateExecutiveQR(ctx context.Context, in *GenerateExecutiveQRRequest, opts ...grpc.CallOption) (*GenerateExecutiveQRResponse, error)
	// Generates bulk student credential QR codes for an admission batch
	GenerateBulkStudentQR(ctx context.Context, in *GenerateBulkStudentQRRequest, opts ...grpc.CallOption) (*GenerateBulkStudentQRResponse, error)
	// Validates a scanned single-use claim token and returns profile details
	ValidateClaimToken(ctx context.Context, in *ValidateClaimTokenRequest, opts ...grpc.CallOption) (*ValidateClaimTokenResponse, error)
	// Verifies device SIM telephony binding and triggers an SMS OTP
	VerifySIMAndSendOTP(ctx context.Context, in *VerifySIMAndSendOTPRequest, opts ...grpc.CallOption) (*VerifySIMAndSendOTPResponse, error)
	// Verifies the SMS OTP, sets the initial password, and claims the account
	VerifyOTPAndClaimAccount(ctx context.Context, in *VerifyOTPAndClaimAccountRequest, opts ...grpc.CallOption) (*VerifyOTPAndClaimAccountResponse, error)
	// Universal authentication endpoint for active users
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Refreshes an access token using a rotating family refresh token
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	// Revokes a user session and invalidates the token family
	RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*RevokeSessionResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) BootstrapSuperAdmin(ctx context.Context, in *BootstrapSuperAdminRequest, opts ...grpc.CallOption) (*BootstrapSuperAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootstrapSuperAdminResponse)
	err := c.cc.Invoke(ctx, AuthService_BootstrapSuperAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GenerateExecutiveQR(ctx context.Context, in *GenerateExecutiveQRRequest, opts ...grpc.CallOption) (*GenerateExecutiveQRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateExecutiveQRResponse)
	err := c.cc.Invoke(ctx, AuthService_GenerateExecutiveQR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GenerateBulkStudentQR(ctx context.Context, in *GenerateBulkStudentQRRequest, opts ...grpc.CallOption) (*GenerateBulkStudentQRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateBulkStudentQRResponse)
	err := c.cc.Invoke(ctx, AuthService_GenerateBulkStudentQR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ValidateClaimToken(ctx context.Context, in *ValidateClaimTokenRequest, opts ...grpc.CallOption) (*ValidateClaimTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateClaimTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_ValidateClaimToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifySIMAndSendOTP(ctx context.Context, in *VerifySIMAndSendOTPRequest, opts ...grpc.CallOption) (*VerifySIMAndSendOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySIMAndSendOTPResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifySIMAndSendOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyOTPAndClaimAccount(ctx context.Context, in *VerifyOTPAndClaimAccountRequest, opts ...grpc.CallOption) (*VerifyOTPAndClaimAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyOTPAndClaimAccountResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifyOTPAndClaimAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*RevokeSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeSessionResponse)
	err := c.cc.Invoke(ctx, AuthService_RevokeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// Authentication and Identity Provisioning Service
type AuthServiceServer interface {
	// Genesis bootstrap for the Chairperson Super Admin seat via bare-metal CLI
	BootstrapSuperAdmin(context.Context, *BootstrapSuperAdminRequest) (*BootstrapSuperAdminResponse, error)
	// Generates sealed credential QR codes for the Executive Council
	GenerateExecutiveQR(context.Context, *GenerateExecutiveQRRequest) (*GenerateExecutiveQRResponse, error)
	// Generates bulk student credential QR codes for an admission batch
	GenerateBulkStudentQR(context.Context, *GenerateBulkStudentQRRequest) (*GenerateBulkStudentQRResponse, error)
	// Validates a scanned single-use claim token and returns profile details
	ValidateClaimToken(context.Context, *ValidateClaimTokenRequest) (*ValidateClaimTokenResponse, error)
	// Verifies device SIM telephony binding and triggers an SMS OTP
	VerifySIMAndSendOTP(context.Context, *VerifySIMAndSendOTPRequest) (*VerifySIMAndSendOTPResponse, error)
	// Verifies the SMS OTP, sets the initial password, and claims the account
	VerifyOTPAndClaimAccount(context.Context, *VerifyOTPAndClaimAccountRequest) (*VerifyOTPAndClaimAccountResponse, error)
	// Universal authentication endpoint for active users
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Refreshes an access token using a rotating family refresh token
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	// Revokes a user session and invalidates the token family
	RevokeSession(context.Context, *RevokeSessionRequest) (*RevokeSessionResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) BootstrapSuperAdmin(context.Context, *BootstrapSuperAdminRequest) (*BootstrapSuperAdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BootstrapSuperAdmin not implemented")
}
func (UnimplementedAuthServiceServer) GenerateExecutiveQR(context.Context, *GenerateExecutiveQRRequest) (*GenerateExecutiveQRResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateExecutiveQR not implemented")
}
func (UnimplementedAuthServiceServer) GenerateBulkStudentQR(context.Context, *GenerateBulkStudentQRRequest) (*GenerateBulkStudentQRResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateBulkStudentQR not implemented")
}
func (UnimplementedAuthServiceServer) ValidateClaimToken(context.Context, *ValidateClaimTokenRequest) (*ValidateClaimTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateClaimToken not implemented")
}
func (UnimplementedAuthServiceServer) VerifySIMAndSendOTP(context.Context, *VerifySIMAndSendOTPRequest) (*VerifySIMAndSendOTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifySIMAndSendOTP not implemented")
}
func (UnimplementedAuthServiceServer) VerifyOTPAndClaimAccount(context.Context, *VerifyOTPAndClaimAccountRequest) (*VerifyOTPAndClaimAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyOTPAndClaimAccount not implemented")
}
func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedAuthServiceServer) RevokeSession(context.Context, *RevokeSessionRequest) (*RevokeSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeSession not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_BootstrapSuperAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapSuperAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).BootstrapSuperAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_BootstrapSuperAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).BootstrapSuperAdmin(ctx, req.(*BootstrapSuperAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GenerateExecutiveQR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateExecutiveQRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GenerateExecutiveQR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GenerateExecutiveQR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GenerateExecutiveQR(ctx, req.(*GenerateExecutiveQRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GenerateBulkStudentQR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateBulkStudentQRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GenerateBulkStudentQR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GenerateBulkStudentQR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GenerateBulkStudentQR(ctx, req.(*GenerateBulkStudentQRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ValidateClaimToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateClaimTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ValidateClaimToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ValidateClaimToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ValidateClaimToken(ctx, req.(*ValidateClaimTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifySIMAndSendOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySIMAndSendOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifySIMAndSendOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifySIMAndSendOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifySIMAndSendOTP(ctx, req.(*VerifySIMAndSendOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyOTPAndClaimAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOTPAndClaimAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyOTPAndClaimAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyOTPAndClaimAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyOTPAndClaimAccount(ctx, req.(*VerifyOTPAndClaimAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RevokeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RevokeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RevokeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RevokeSession(ctx, req.(*RevokeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "campus.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BootstrapSuperAdmin",
			Handler:    _AuthService_BootstrapSuperAdmin_Handler,
		},
		{
			MethodName: "GenerateExecutiveQR",
			Handler:    _AuthService_GenerateExecutiveQR_Handler,
		},
		{
			MethodName: "GenerateBulkStudentQR",
			Handler:    _AuthService_GenerateBulkStudentQR_Handler,
		},
		{
			MethodName: "ValidateClaimToken",
			Handler:    _AuthService_ValidateClaimToken_Handler,
		},
		{
			MethodName: "VerifySIMAndSendOTP",
			Handler:    _AuthService_VerifySIMAndSendOTP_Handler,
		},
		{
			MethodName: "VerifyOTPAndClaimAccount",
			Handler:    _AuthService_VerifyOTPAndClaimAccount_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AuthService_RefreshToken_Handler,
		},
		{
			MethodName: "RevokeSession",
			Handler:    _AuthService_RevokeSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "campus/v1/auth.proto",
}
