// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: campus/v1/auth.proto

package campusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Executive role enumeration for Tier-1 executive provisioning
type ExecutiveRole int32

const (
	ExecutiveRole_EXECUTIVE_ROLE_UNSPECIFIED        ExecutiveRole = 0
	ExecutiveRole_EXECUTIVE_ROLE_DIRECTOR           ExecutiveRole = 1
	ExecutiveRole_EXECUTIVE_ROLE_EXECUTIVE_DIRECTOR ExecutiveRole = 2
	ExecutiveRole_EXECUTIVE_ROLE_DEAN               ExecutiveRole = 3
	ExecutiveRole_EXECUTIVE_ROLE_REGISTRAR          ExecutiveRole = 4
)

// Enum value maps for ExecutiveRole.
var (
	ExecutiveRole_name = map[int32]string{
		0: "EXECUTIVE_ROLE_UNSPECIFIED",
		1: "EXECUTIVE_ROLE_DIRECTOR",
		2: "EXECUTIVE_ROLE_EXECUTIVE_DIRECTOR",
		3: "EXECUTIVE_ROLE_DEAN",
		4: "EXECUTIVE_ROLE_REGISTRAR",
	}
	ExecutiveRole_value = map[string]int32{
		"EXECUTIVE_ROLE_UNSPECIFIED":        0,
		"EXECUTIVE_ROLE_DIRECTOR":           1,
		"EXECUTIVE_ROLE_EXECUTIVE_DIRECTOR": 2,
		"EXECUTIVE_ROLE_DEAN":               3,
		"EXECUTIVE_ROLE_REGISTRAR":          4,
	}
)

func (x ExecutiveRole) Enum() *ExecutiveRole {
	p := new(ExecutiveRole)
	*p = x
	return p
}

func (x ExecutiveRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutiveRole) Descriptor() protoreflect.EnumDescriptor {
	return file_campus_v1_auth_proto_enumTypes[0].Descriptor()
}

func (ExecutiveRole) Type() protoreflect.EnumType {
	return &file_campus_v1_auth_proto_enumTypes[0]
}

func (x ExecutiveRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutiveRole.Descriptor instead.
func (ExecutiveRole) EnumDescriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{0}
}

// Genesis Super Admin (Chairperson) bootstrap request
type BootstrapSuperAdminRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChairpersonName  string                 `protobuf:"bytes,1,opt,name=chairperson_name,json=chairpersonName,proto3" json:"chairperson_name,omitempty"`
	ChairpersonEmail string                 `protobuf:"bytes,2,opt,name=chairperson_email,json=chairpersonEmail,proto3" json:"chairperson_email,omitempty"`
	ChairpersonPhone string                 `protobuf:"bytes,3,opt,name=chairperson_phone,json=chairpersonPhone,proto3" json:"chairperson_phone,omitempty"`
	Blank            bool                   `protobuf:"varint,4,opt,name=blank,proto3" json:"blank,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BootstrapSuperAdminRequest) Reset() {
	*x = BootstrapSuperAdminRequest{}
	mi := &file_campus_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapSuperAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapSuperAdminRequest) ProtoMessage() {}

func (x *BootstrapSuperAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapSuperAdminRequest.ProtoReflect.Descriptor instead.
func (*BootstrapSuperAdminRequest) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *BootstrapSuperAdminRequest) GetChairpersonName() string {
	if x != nil {
		return x.ChairpersonName
	}
	return ""
}

func (x *BootstrapSuperAdminRequest) GetChairpersonEmail() string {
	if x != nil {
		return x.ChairpersonEmail
	}
	return ""
}

func (x *BootstrapSuperAdminRequest) GetChairpersonPhone() string {
	if x != nil {
		return x.ChairpersonPhone
	}
	return ""
}

func (x *BootstrapSuperAdminRequest) GetBlank() bool {
	if x != nil {
		return x.Blank
	}
	return false
}

// Genesis Super Admin (Chairperson) bootstrap response
type BootstrapSuperAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimToken    string                 `protobuf:"bytes,1,opt,name=claim_token,json=claimToken,proto3" json:"claim_token,omitempty"`
	AsciiQr       string                 `protobuf:"bytes,2,opt,name=ascii_qr,json=asciiQr,proto3" json:"ascii_qr,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapSuperAdminResponse) Reset() {
	*x = BootstrapSuperAdminResponse{}
	mi := &file_campus_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapSuperAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapSuperAdminResponse) ProtoMessage() {}

func (x *BootstrapSuperAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapSuperAdminResponse.ProtoReflect.Descriptor instead.
func (*BootstrapSuperAdminResponse) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *BootstrapSuperAdminResponse) GetClaimToken() string {
	if x != nil {
		return x.ClaimToken
	}
	return ""
}

func (x *BootstrapSuperAdminResponse) GetAsciiQr() string {
	if x != nil {
		return x.AsciiQr
	}
	return ""
}

func (x *BootstrapSuperAdminResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

// Request to generate an executive credential QR code
type GenerateExecutiveQRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *RequestMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Role          ExecutiveRole          `protobuf:"varint,2,opt,name=role,proto3,enum=campus.v1.ExecutiveRole" json:"role,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateExecutiveQRRequest) Reset() {
	*x = GenerateExecutiveQRRequest{}
	mi := &file_campus_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateExecutiveQRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateExecutiveQRRequest) ProtoMessage() {}

func (x *GenerateExecutiveQRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateExecutiveQRRequest.ProtoReflect.Descriptor instead.
func (*GenerateExecutiveQRRequest) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateExecutiveQRRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GenerateExecutiveQRRequest) GetRole() ExecutiveRole {
	if x != nil {
		return x.Role
	}
	return ExecutiveRole_EXECUTIVE_ROLE_UNSPECIFIED
}

func (x *GenerateExecutiveQRRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *GenerateExecutiveQRRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GenerateExecutiveQRRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

// Response containing the executive sealed QR payload
type GenerateExecutiveQRResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClaimToken      string                 `protobuf:"bytes,1,opt,name=claim_token,json=claimToken,proto3" json:"claim_token,omitempty"`
	SealedQrPayload string                 `protobuf:"bytes,2,opt,name=sealed_qr_payload,json=sealedQrPayload,proto3" json:"sealed_qr_payload,omitempty"`
	ExpiresAtUnix   int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateExecutiveQRResponse) Reset() {
	*x = GenerateExecutiveQRResponse{}
	mi := &file_campus_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateExecutiveQRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateExecutiveQRResponse) ProtoMessage() {}

func (x *GenerateExecutiveQRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateExecutiveQRResponse.ProtoReflect.Descriptor instead.
func (*GenerateExecutiveQRResponse) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateExecutiveQRResponse) GetClaimToken() string {
	if x != nil {
		return x.ClaimToken
	}
	return ""
}

func (x *GenerateExecutiveQRResponse) GetSealedQrPayload() string {
	if x != nil {
		return x.SealedQrPayload
	}
	return ""
}

func (x *GenerateExecutiveQRResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

// Request to generate bulk student credential QR codes
type GenerateBulkStudentQRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *RequestMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	BatchYear     string                 `protobuf:"bytes,2,opt,name=batch_year,json=batchYear,proto3" json:"batch_year,omitempty"`
	DepartmentId  string                 `protobuf:"bytes,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,4,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateBulkStudentQRRequest) Reset() {
	*x = GenerateBulkStudentQRRequest{}
	mi := &file_campus_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateBulkStudentQRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateBulkStudentQRRequest) ProtoMessage() {}

func (x *GenerateBulkStudentQRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateBulkStudentQRRequest.ProtoReflect.Descriptor instead.
func (*GenerateBulkStudentQRRequest) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateBulkStudentQRRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GenerateBulkStudentQRRequest) GetBatchYear() string {
	if x != nil {
		return x.BatchYear
	}
	return ""
}

func (x *GenerateBulkStudentQRRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *GenerateBulkStudentQRRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

// Individual student claim entry within a bulk batch
type StudentClaimEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StudentId       string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	RollNumber      string                 `protobuf:"bytes,2,opt,name=roll_number,json=rollNumber,proto3" json:"roll_number,omitempty"`
	Prn             string                 `protobuf:"bytes,3,opt,name=prn,proto3" json:"prn,omitempty"`
	Username        string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	ClaimToken      string                 `protobuf:"bytes,5,opt,name=claim_token,json=claimToken,proto3" json:"claim_token,omitempty"`
	SealedQrPayload string                 `protobuf:"bytes,6,opt,name=sealed_qr_payload,json=sealedQrPayload,proto3" json:"sealed_qr_payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StudentClaimEntry) Reset() {
	*x = StudentClaimEntry{}
	mi := &file_campus_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentClaimEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentClaimEntry) ProtoMessage() {}

func (x *StudentClaimEntry) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentClaimEntry.ProtoReflect.Descriptor instead.
func (*StudentClaimEntry) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *StudentClaimEntry) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentClaimEntry) GetRollNumber() string {
	if x != nil {
		return x.RollNumber
	}
	return ""
}

func (x *StudentClaimEntry) GetPrn() string {
	if x != nil {
		return x.Prn
	}
	return ""
}

func (x *StudentClaimEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *StudentClaimEntry) GetClaimToken() string {
	if x != nil {
		return x.ClaimToken
	}
	return ""
}

func (x *StudentClaimEntry) GetSealedQrPayload() string {
	if x != nil {
		return x.SealedQrPayload
	}
	return ""
}

// Response containing bulk student credential QR codes
type GenerateBulkStudentQRResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BatchId        string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	TotalGenerated int32                  `protobuf:"varint,2,opt,name=total_generated,json=totalGenerated,proto3" json:"total_generated,omitempty"`
	ManifestHash   string                 `protobuf:"bytes,3,opt,name=manifest_hash,json=manifestHash,proto3" json:"manifest_hash,omitempty"`
	Students       []*StudentClaimEntry   `protobuf:"bytes,4,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateBulkStudentQRResponse) Reset() {
	*x = GenerateBulkStudentQRResponse{}
	mi := &file_campus_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateBulkStudentQRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateBulkStudentQRResponse) ProtoMessage() {}

func (x *GenerateBulkStudentQRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateBulkStudentQRResponse.ProtoReflect.Descriptor instead.
func (*GenerateBulkStudentQRResponse) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateBulkStudentQRResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *GenerateBulkStudentQRResponse) GetTotalGenerated() int32 {
	if x != nil {
		return x.TotalGenerated
	}
	return 0
}

func (x *GenerateBulkStudentQRResponse) GetManifestHash() string {
	if x != nil {
		return x.ManifestHash
	}
	return ""
}

func (x *GenerateBulkStudentQRResponse) GetStudents() []*StudentClaimEntry {
	if x != nil {
		return x.Students
	}
	return nil
}

// Request to validate a scanned claim token
type ValidateClaimTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimToken    string                 `protobuf:"bytes,1,opt,name=claim_token,json=claimToken,proto3" json:"claim_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateClaimTokenRequest) Reset() {
	*x = ValidateClaimTokenRequest{}
	mi := &file_campus_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateClaimTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateClaimTokenRequest) ProtoMessage() {}

func (x *ValidateClaimTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateClaimTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateClaimTokenRequest) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateClaimTokenRequest) GetClaimToken() string {
	if x != nil {
		return x.ClaimToken
	}
	return ""
}

// Response with student/executive details for the claim token
type ValidateClaimTokenResponse struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	IsValid                     bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	UserId                      string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MaskedPhoneNumber           string                 `protobuf:"bytes,3,opt,name=masked_phone_number,json=maskedPhoneNumber,proto3" json:"masked_phone_number,omitempty"`
	Username                    string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	AcademicName                string                 `protobuf:"bytes,5,opt,name=academic_name,json=academicName,proto3" json:"academic_name,omitempty"`
	LegalFullName               string                 `protobuf:"bytes,6,opt,name=legal_full_name,json=legalFullName,proto3" json:"legal_full_name,omitempty"`
	AdmissionType               string                 `protobuf:"bytes,7,opt,name=admission_type,json=admissionType,proto3" json:"admission_type,omitempty"`
	EntrySemesterNumber         int32                  `protobuf:"varint,8,opt,name=entry_semester_number,json=entrySemesterNumber,proto3" json:"entry_semester_number,omitempty"`
	LateralEntrySummary         string                 `protobuf:"bytes,9,opt,name=lateral_entry_summary,json=lateralEntrySummary,proto3" json:"lateral_entry_summary,omitempty"`
	GracePeriodRemainingSeconds int64                  `protobuf:"varint,10,opt,name=grace_period_remaining_seconds,json=gracePeriodRemainingSeconds,proto3" json:"grace_period_remaining_seconds,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ValidateClaimTokenResponse) Reset() {
	*x = ValidateClaimTokenResponse{}
	mi := &file_campus_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateClaimTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateClaimTokenResponse) ProtoMessage() {}

func (x *ValidateClaimTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateClaimTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateClaimTokenResponse) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateClaimTokenResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateClaimTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateClaimTokenResponse) GetMaskedPhoneNumber() string {
	if x != nil {
		return x.MaskedPhoneNumber
	}
	return ""
}

func (x *ValidateClaimTokenResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ValidateClaimTokenResponse) GetAcademicName() string {
	if x != nil {
		return x.AcademicName
	}
	return ""
}

func (x *ValidateClaimTokenResponse) GetLegalFullName() string {
	if x != nil {
		return x.LegalFullName
	}
	return ""
}

func (x *ValidateClaimTokenResponse) GetAdmissionType() string {
	if x != nil {
		return x.AdmissionType
	}
	return ""
}

func (x *ValidateClaimTokenResponse) GetEntrySemesterNumber() int32 {
	if x != nil {
		return x.EntrySemesterNumber
	}
	return 0
}

func (x *ValidateClaimTokenResponse) GetLateralEntrySummary() string {
	if x != nil {
		return x.LateralEntrySummary
	}
	return ""
}

func (x *ValidateClaimTokenResponse) GetGracePeriodRemainingSeconds() int64 {
	if x != nil {
		return x.GracePeriodRemainingSeconds
	}
	return 0
}

// Request to verify hardware SIM presence and send an SMS OTP
type VerifySIMAndSendOTPRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClaimToken         string                 `protobuf:"bytes,1,opt,name=claim_token,json=claimToken,proto3" json:"claim_token,omitempty"`
	DeviceSimIccidHash string                 `protobuf:"bytes,2,opt,name=device_sim_iccid_hash,json=deviceSimIccidHash,proto3" json:"device_sim_iccid_hash,omitempty"`
	DeviceCarrierPhone string                 `protobuf:"bytes,3,opt,name=device_carrier_phone,json=deviceCarrierPhone,proto3" json:"device_carrier_phone,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VerifySIMAndSendOTPRequest) Reset() {
	*x = VerifySIMAndSendOTPRequest{}
	mi := &file_campus_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySIMAndSendOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySIMAndSendOTPRequest) ProtoMessage() {}

func (x *VerifySIMAndSendOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySIMAndSendOTPRequest.ProtoReflect.Descriptor instead.
func (*VerifySIMAndSendOTPRequest) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *VerifySIMAndSendOTPRequest) GetClaimToken() string {
	if x != nil {
		return x.ClaimToken
	}
	return ""
}

func (x *VerifySIMAndSendOTPRequest) GetDeviceSimIccidHash() string {
	if x != nil {
		return x.DeviceSimIccidHash
	}
	return ""
}

func (x *VerifySIMAndSendOTPRequest) GetDeviceCarrierPhone() string {
	if x != nil {
		return x.DeviceCarrierPhone
	}
	return ""
}

// Response confirming hardware SIM match and OTP dispatch
type VerifySIMAndSendOTPResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SimMatched               bool                   `protobuf:"varint,1,opt,name=sim_matched,json=simMatched,proto3" json:"sim_matched,omitempty"`
	OtpChallengeId           string                 `protobuf:"bytes,2,opt,name=otp_challenge_id,json=otpChallengeId,proto3" json:"otp_challenge_id,omitempty"`
	ResendAvailableInSeconds int32                  `protobuf:"varint,3,opt,name=resend_available_in_seconds,json=resendAvailableInSeconds,proto3" json:"resend_available_in_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *VerifySIMAndSendOTPResponse) Reset() {
	*x = VerifySIMAndSendOTPResponse{}
	mi := &file_campus_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySIMAndSendOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySIMAndSendOTPResponse) ProtoMessage() {}

func (x *VerifySIMAndSendOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySIMAndSendOTPResponse.ProtoReflect.Descriptor instead.
func (*VerifySIMAndSendOTPResponse) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *VerifySIMAndSendOTPResponse) GetSimMatched() bool {
	if x != nil {
		return x.SimMatched
	}
	return false
}

func (x *VerifySIMAndSendOTPResponse) GetOtpChallengeId() string {
	if x != nil {
		return x.OtpChallengeId
	}
	return ""
}

func (x *VerifySIMAndSendOTPResponse) GetResendAvailableInSeconds() int32 {
	if x != nil {
		return x.ResendAvailableInSeconds
	}
	return 0
}

// Request to verify SMS OTP and set the initial account password
type VerifyOTPAndClaimAccountRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ClaimToken             string                 `protobuf:"bytes,1,opt,name=claim_token,json=claimToken,proto3" json:"claim_token,omitempty"`
	OtpChallengeId         string                 `protobuf:"bytes,2,opt,name=otp_challenge_id,json=otpChallengeId,proto3" json:"otp_challenge_id,omitempty"`
	OtpCode                string                 `protobuf:"bytes,3,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	NewPassword            string                 `protobuf:"bytes,4,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	EnableBiometrics       bool                   `protobuf:"varint,5,opt,name=enable_biometrics,json=enableBiometrics,proto3" json:"enable_biometrics,omitempty"`
	TotpSecretConfirmation string                 `protobuf:"bytes,6,opt,name=totp_secret_confirmation,json=totpSecretConfirmation,proto3" json:"totp_secret_confirmation,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *VerifyOTPAndClaimAccountRequest) Reset() {
	*x = VerifyOTPAndClaimAccountRequest{}
	mi := &file_campus_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOTPAndClaimAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPAndClaimAccountRequest) ProtoMessage() {}

func (x *VerifyOTPAndClaimAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPAndClaimAccountRequest.ProtoReflect.Descriptor instead.
func (*VerifyOTPAndClaimAccountRequest) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyOTPAndClaimAccountRequest) GetClaimToken() string {
	if x != nil {
		return x.ClaimToken
	}
	return ""
}

func (x *VerifyOTPAndClaimAccountRequest) GetOtpChallengeId() string {
	if x != nil {
		return x.OtpChallengeId
	}
	return ""
}

func (x *VerifyOTPAndClaimAccountRequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

func (x *VerifyOTPAndClaimAccountRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *VerifyOTPAndClaimAccountRequest) GetEnableBiometrics() bool {
	if x != nil {
		return x.EnableBiometrics
	}
	return false
}

func (x *VerifyOTPAndClaimAccountRequest) GetTotpSecretConfirmation() string {
	if x != nil {
		return x.TotpSecretConfirmation
	}
	return ""
}

// Response confirming successful account claim and returning sessions
type VerifyOTPAndClaimAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	RoleCode      string                 `protobuf:"bytes,7,opt,name=role_code,json=roleCode,proto3" json:"role_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOTPAndClaimAccountResponse) Reset() {
	*x = VerifyOTPAndClaimAccountResponse{}
	mi := &file_campus_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOTPAndClaimAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPAndClaimAccountResponse) ProtoMessage() {}

func (x *VerifyOTPAndClaimAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPAndClaimAccountResponse.ProtoReflect.Descriptor instead.
func (*VerifyOTPAndClaimAccountResponse) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyOTPAndClaimAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyOTPAndClaimAccountResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *VerifyOTPAndClaimAccountResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *VerifyOTPAndClaimAccountResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyOTPAndClaimAccountResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifyOTPAndClaimAccountResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyOTPAndClaimAccountResponse) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

// Universal login request supporting username, email, or PRN
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	TotpCode      string                 `protobuf:"bytes,3,opt,name=totp_code,json=totpCode,proto3" json:"totp_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_campus_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *LoginRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetTotpCode() string {
	if x != nil {
		return x.TotpCode
	}
	return ""
}

// Login response containing Ed25519 JWT session tokens
type LoginResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresInSeconds int64                  `protobuf:"varint,3,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	UserId           string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username         string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	FullName         string                 `protobuf:"bytes,6,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	RoleCodes        []string               `protobuf:"bytes,7,rep,name=role_codes,json=roleCodes,proto3" json:"role_codes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_campus_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *LoginResponse) GetRoleCodes() []string {
	if x != nil {
		return x.RoleCodes
	}
	return nil
}

// Session refresh token request
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_campus_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// Session refresh token response with family token rotation
type RefreshTokenResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresInSeconds int64                  `protobuf:"varint,3,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_campus_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

// Session revocation request
type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *RequestMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_campus_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *RevokeSessionRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *RevokeSessionRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// Session revocation response
type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_campus_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_campus_v1_auth_proto_rawDescGZIP(), []int{18}
}

func (x *RevokeSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_campus_v1_auth_proto protoreflect.FileDescriptor

const file_campus_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x14campus/v1/auth.proto\x12\tcampus.v1\x1a\x16campus/v1/common.proto\"\xb7\x01\n" +
	"\x1aBootstrapSuperAdminRequest\x12)\n" +
	"\x10chairperson_name\x18\x01 \x01(\tR\x0fchairpersonName\x12+\n" +
	"\x11chairperson_email\x18\x02 \x01(\tR\x10chairpersonEmail\x12+\n" +
	"\x11chairperson_phone\x18\x03 \x01(\tR\x10chairpersonPhone\x12\x14\n" +
	"\x05blank\x18\x04 \x01(\bR\x05blank\"\x81\x01\n" +
	"\x1bBootstrapSuperAdminResponse\x12\x1f\n" +
	"\vclaim_token\x18\x01 \x01(\tR\n" +
	"claimToken\x12\x19\n" +
	"\bascii_qr\x18\x02 \x01(\tR\aasciiQr\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\"\xcc\x01\n" +
	"\x1aGenerateExecutiveQRRequest\x12*\n" +
	"\x04meta\x18\x01 \x01(\v2\x16.campus.v1.RequestMetaR\x04meta\x12,\n" +
	"\x04role\x18\x02 \x01(\x0e2\x18.campus.v1.ExecutiveRoleR\x04role\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\"\x92\x01\n" +
	"\x1bGenerateExecutiveQRResponse\x12\x1f\n" +
	"\vclaim_token\x18\x01 \x01(\tR\n" +
	"claimToken\x12*\n" +
	"\x11sealed_qr_payload\x18\x02 \x01(\tR\x0fsealedQrPayload\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\"\xab\x01\n" +
	"\x1cGenerateBulkStudentQRRequest\x12*\n" +
	"\x04meta\x18\x01 \x01(\v2\x16.campus.v1.RequestMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"batch_year\x18\x02 \x01(\tR\tbatchYear\x12#\n" +
	"\rdepartment_id\x18\x03 \x01(\tR\fdepartmentId\x12\x1b\n" +
	"\tcourse_id\x18\x04 \x01(\tR\bcourseId\"\xce\x01\n" +
	"\x11StudentClaimEntry\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1f\n" +
	"\vroll_number\x18\x02 \x01(\tR\n" +
	"rollNumber\x12\x10\n" +
	"\x03prn\x18\x03 \x01(\tR\x03prn\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1f\n" +
	"\vclaim_token\x18\x05 \x01(\tR\n" +
	"claimToken\x12*\n" +
	"\x11sealed_qr_payload\x18\x06 \x01(\tR\x0fsealedQrPayload\"\xc2\x01\n" +
	"\x1dGenerateBulkStudentQRResponse\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12'\n" +
	"\x0ftotal_generated\x18\x02 \x01(\x05R\x0etotalGenerated\x12#\n" +
	"\rmanifest_hash\x18\x03 \x01(\tR\fmanifestHash\x128\n" +
	"\bstudents\x18\x04 \x03(\v2\x1c.campus.v1.StudentClaimEntryR\bstudents\"<\n" +
	"\x19ValidateClaimTokenRequest\x12\x1f\n" +
	"\vclaim_token\x18\x01 \x01(\tR\n" +
	"claimToken\"\xbd\x03\n" +
	"\x1aValidateClaimTokenResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12.\n" +
	"\x13masked_phone_number\x18\x03 \x01(\tR\x11maskedPhoneNumber\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12#\n" +
	"\racademic_name\x18\x05 \x01(\tR\facademicName\x12&\n" +
	"\x0flegal_full_name\x18\x06 \x01(\tR\rlegalFullName\x12%\n" +
	"\x0eadmission_type\x18\a \x01(\tR\radmissionType\x122\n" +
	"\x15entry_semester_number\x18\b \x01(\x05R\x13entrySemesterNumber\x122\n" +
	"\x15lateral_entry_summary\x18\t \x01(\tR\x13lateralEntrySummary\x12C\n" +
	"\x1egrace_period_remaining_seconds\x18\n" +
	" \x01(\x03R\x1bgracePeriodRemainingSeconds\"\xa2\x01\n" +
	"\x1aVerifySIMAndSendOTPRequest\x12\x1f\n" +
	"\vclaim_token\x18\x01 \x01(\tR\n" +
	"claimToken\x121\n" +
	"\x15device_sim_iccid_hash\x18\x02 \x01(\tR\x12deviceSimIccidHash\x120\n" +
	"\x14device_carrier_phone\x18\x03 \x01(\tR\x12deviceCarrierPhone\"\xa7\x01\n" +
	"\x1bVerifySIMAndSendOTPResponse\x12\x1f\n" +
	"\vsim_matched\x18\x01 \x01(\bR\n" +
	"simMatched\x12(\n" +
	"\x10otp_challenge_id\x18\x02 \x01(\tR\x0eotpChallengeId\x12=\n" +
	"\x1bresend_available_in_seconds\x18\x03 \x01(\x05R\x18resendAvailableInSeconds\"\x91\x02\n" +
	"\x1fVerifyOTPAndClaimAccountRequest\x12\x1f\n" +
	"\vclaim_token\x18\x01 \x01(\tR\n" +
	"claimToken\x12(\n" +
	"\x10otp_challenge_id\x18\x02 \x01(\tR\x0eotpChallengeId\x12\x19\n" +
	"\botp_code\x18\x03 \x01(\tR\aotpCode\x12!\n" +
	"\fnew_password\x18\x04 \x01(\tR\vnewPassword\x12+\n" +
	"\x11enable_biometrics\x18\x05 \x01(\bR\x10enableBiometrics\x128\n" +
	"\x18totp_secret_confirmation\x18\x06 \x01(\tR\x16totpSecretConfirmation\"\xec\x01\n" +
	" VerifyOTPAndClaimAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x1b\n" +
	"\trole_code\x18\a \x01(\tR\broleCode\"g\n" +
	"\fLoginRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\ttotp_code\x18\x03 \x01(\tR\btotpCode\"\xf6\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12,\n" +
	"\x12expires_in_seconds\x18\x03 \x01(\x03R\x10expiresInSeconds\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\x06 \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"role_codes\x18\a \x03(\tR\troleCodes\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x8c\x01\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12,\n" +
	"\x12expires_in_seconds\x18\x03 \x01(\x03R\x10expiresInSeconds\"g\n" +
	"\x14RevokeSessionRequest\x12*\n" +
	"\x04meta\x18\x01 \x01(\v2\x16.campus.v1.RequestMetaR\x04meta\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"1\n" +
	"\x15RevokeSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\xaa\x01\n" +
	"\rExecutiveRole\x12\x1e\n" +
	"\x1aEXECUTIVE_ROLE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EXECUTIVE_ROLE_DIRECTOR\x10\x01\x12%\n" +
	"!EXECUTIVE_ROLE_EXECUTIVE_DIRECTOR\x10\x02\x12\x17\n" +
	"\x13EXECUTIVE_ROLE_DEAN\x10\x03\x12\x1c\n" +
	"\x18EXECUTIVE_ROLE_REGISTRAR\x10\x042\xe4\x06\n" +
	"\vAuthService\x12d\n" +
	"\x13BootstrapSuperAdmin\x12%.campus.v1.BootstrapSuperAdminRequest\x1a&.campus.v1.BootstrapSuperAdminResponse\x12d\n" +
	"\x13GenerateExecutiveQR\x12%.campus.v1.GenerateExecutiveQRRequest\x1a&.campus.v1.GenerateExecutiveQRResponse\x12j\n" +
	"\x15GenerateBulkStudentQR\x12'.campus.v1.GenerateBulkStudentQRRequest\x1a(.campus.v1.GenerateBulkStudentQRResponse\x12a\n" +
	"\x12ValidateClaimToken\x12$.campus.v1.ValidateClaimTokenRequest\x1a%.campus.v1.ValidateClaimTokenResponse\x12d\n" +
	"\x13VerifySIMAndSendOTP\x12%.campus.v1.VerifySIMAndSendOTPRequest\x1a&.campus.v1.VerifySIMAndSendOTPResponse\x12s\n" +
	"\x18VerifyOTPAndClaimAccount\x12*.campus.v1.VerifyOTPAndClaimAccountRequest\x1a+.campus.v1.VerifyOTPAndClaimAccountResponse\x12:\n" +
	"\x05Login\x12\x17.campus.v1.LoginRequest\x1a\x18.campus.v1.LoginResponse\x12O\n" +
	"\fRefreshToken\x12\x1e.campus.v1.RefreshTokenRequest\x1a\x1f.campus.v1.RefreshTokenResponse\x12R\n" +
	"\rRevokeSession\x12\x1f.campus.v1.RevokeSessionRequest\x1a .campus.v1.RevokeSessionResponseBSZQgithub.com/Yogesh-Kumar-Mallik-dev/campus-os/backend/pkg/proto/campus/v1;campusv1b\x06proto3"

var (
	file_campus_v1_auth_proto_rawDescOnce sync.Once
	file_campus_v1_auth_proto_rawDescData []byte
)

func file_campus_v1_auth_proto_rawDescGZIP() []byte {
	file_campus_v1_auth_proto_rawDescOnce.Do(func() {
		file_campus_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_campus_v1_auth_proto_rawDesc), len(file_campus_v1_auth_proto_rawDesc)))
	})
	return file_campus_v1_auth_proto_rawDescData
}

var file_campus_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_campus_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_campus_v1_auth_proto_goTypes = []any{
	(ExecutiveRole)(0),                       // 0: campus.v1.ExecutiveRole
	(*BootstrapSuperAdminRequest)(nil),       // 1: campus.v1.BootstrapSuperAdminRequest
	(*BootstrapSuperAdminResponse)(nil),      // 2: campus.v1.BootstrapSuperAdminResponse
	(*GenerateExecutiveQRRequest)(nil),       // 3: campus.v1.GenerateExecutiveQRRequest
	(*GenerateExecutiveQRResponse)(nil),      // 4: campus.v1.GenerateExecutiveQRResponse
	(*GenerateBulkStudentQRRequest)(nil),     // 5: campus.v1.GenerateBulkStudentQRRequest
	(*StudentClaimEntry)(nil),                // 6: campus.v1.StudentClaimEntry
	(*GenerateBulkStudentQRResponse)(nil),    // 7: campus.v1.GenerateBulkStudentQRResponse
	(*ValidateClaimTokenRequest)(nil),        // 8: campus.v1.ValidateClaimTokenRequest
	(*ValidateClaimTokenResponse)(nil),       // 9: campus.v1.ValidateClaimTokenResponse
	(*VerifySIMAndSendOTPRequest)(nil),       // 10: campus.v1.VerifySIMAndSendOTPRequest
	(*VerifySIMAndSendOTPResponse)(nil),      // 11: campus.v1.VerifySIMAndSendOTPResponse
	(*VerifyOTPAndClaimAccountRequest)(nil),  // 12: campus.v1.VerifyOTPAndClaimAccountRequest
	(*VerifyOTPAndClaimAccountResponse)(nil), // 13: campus.v1.VerifyOTPAndClaimAccountResponse
	(*LoginRequest)(nil),                     // 14: campus.v1.LoginRequest
	(*LoginResponse)(nil),                    // 15: campus.v1.LoginResponse
	(*RefreshTokenRequest)(nil),              // 16: campus.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),             // 17: campus.v1.RefreshTokenResponse
	(*RevokeSessionRequest)(nil),             // 18: campus.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),            // 19: campus.v1.RevokeSessionResponse
	(*RequestMeta)(nil),                      // 20: campus.v1.RequestMeta
}
var file_campus_v1_auth_proto_depIdxs = []int32{
	20, // 0: campus.v1.GenerateExecutiveQRRequest.meta:type_name -> campus.v1.RequestMeta
	0,  // 1: campus.v1.GenerateExecutiveQRRequest.role:type_name -> campus.v1.ExecutiveRole
	20, // 2: campus.v1.GenerateBulkStudentQRRequest.meta:type_name -> campus.v1.RequestMeta
	6,  // 3: campus.v1.GenerateBulkStudentQRResponse.students:type_name -> campus.v1.StudentClaimEntry
	20, // 4: campus.v1.RevokeSessionRequest.meta:type_name -> campus.v1.RequestMeta
	1,  // 5: campus.v1.AuthService.BootstrapSuperAdmin:input_type -> campus.v1.BootstrapSuperAdminRequest
	3,  // 6: campus.v1.AuthService.GenerateExecutiveQR:input_type -> campus.v1.GenerateExecutiveQRRequest
	5,  // 7: campus.v1.AuthService.GenerateBulkStudentQR:input_type -> campus.v1.GenerateBulkStudentQRRequest
	8,  // 8: campus.v1.AuthService.ValidateClaimToken:input_type -> campus.v1.ValidateClaimTokenRequest
	10, // 9: campus.v1.AuthService.VerifySIMAndSendOTP:input_type -> campus.v1.VerifySIMAndSendOTPRequest
	12, // 10: campus.v1.AuthService.VerifyOTPAndClaimAccount:input_type -> campus.v1.VerifyOTPAndClaimAccountRequest
	14, // 11: campus.v1.AuthService.Login:input_type -> campus.v1.LoginRequest
	16, // 12: campus.v1.AuthService.RefreshToken:input_type -> campus.v1.RefreshTokenRequest
	18, // 13: campus.v1.AuthService.RevokeSession:input_type -> campus.v1.RevokeSessionRequest
	2,  // 14: campus.v1.AuthService.BootstrapSuperAdmin:output_type -> campus.v1.BootstrapSuperAdminResponse
	4,  // 15: campus.v1.AuthService.GenerateExecutiveQR:output_type -> campus.v1.GenerateExecutiveQRResponse
	7,  // 16: campus.v1.AuthService.GenerateBulkStudentQR:output_type -> campus.v1.GenerateBulkStudentQRResponse
	9,  // 17: campus.v1.AuthService.ValidateClaimToken:output_type -> campus.v1.ValidateClaimTokenResponse
	11, // 18: campus.v1.AuthService.VerifySIMAndSendOTP:output_type -> campus.v1.VerifySIMAndSendOTPResponse
	13, // 19: campus.v1.AuthService.VerifyOTPAndClaimAccount:output_type -> campus.v1.VerifyOTPAndClaimAccountResponse
	15, // 20: campus.v1.AuthService.Login:output_type -> campus.v1.LoginResponse
	17, // 21: campus.v1.AuthService.RefreshToken:output_type -> campus.v1.RefreshTokenResponse
	19, // 22: campus.v1.AuthService.RevokeSession:output_type -> campus.v1.RevokeSessionResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_campus_v1_auth_proto_init() }
func file_campus_v1_auth_proto_init() {
	if File_campus_v1_auth_proto != nil {
		return
	}
	file_campus_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_campus_v1_auth_proto_rawDesc), len(file_campus_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_campus_v1_auth_proto_goTypes,
		DependencyIndexes: file_campus_v1_auth_proto_depIdxs,
		EnumInfos:         file_campus_v1_auth_proto_enumTypes,
		MessageInfos:      file_campus_v1_auth_proto_msgTypes,
	}.Build()
	File_campus_v1_auth_proto = out.File
	file_campus_v1_auth_proto_goTypes = nil
	file_campus_v1_auth_proto_depIdxs = nil
}
