// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: campus/v1/common.proto

package campusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request metadata containing transaction lease token and correlation context
type RequestMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	TxToken       string                 `protobuf:"bytes,3,opt,name=tx_token,json=txToken,proto3" json:"tx_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMeta) Reset() {
	*x = RequestMeta{}
	mi := &file_campus_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMeta) ProtoMessage() {}

func (x *RequestMeta) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMeta.ProtoReflect.Descriptor instead.
func (*RequestMeta) Descriptor() ([]byte, []int) {
	return file_campus_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMeta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestMeta) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *RequestMeta) GetTxToken() string {
	if x != nil {
		return x.TxToken
	}
	return ""
}

// Transaction session initiation
type BeginTxRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BeginTxRequest) Reset() {
	*x = BeginTxRequest{}
	mi := &file_campus_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTxRequest) ProtoMessage() {}

func (x *BeginTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTxRequest.ProtoReflect.Descriptor instead.
func (*BeginTxRequest) Descriptor() ([]byte, []int) {
	return file_campus_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *BeginTxRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BeginTxRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type BeginTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxToken       string                 `protobuf:"bytes,1,opt,name=tx_token,json=txToken,proto3" json:"tx_token,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,2,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTxResponse) Reset() {
	*x = BeginTxResponse{}
	mi := &file_campus_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTxResponse) ProtoMessage() {}

func (x *BeginTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTxResponse.ProtoReflect.Descriptor instead.
func (*BeginTxResponse) Descriptor() ([]byte, []int) {
	return file_campus_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *BeginTxResponse) GetTxToken() string {
	if x != nil {
		return x.TxToken
	}
	return ""
}

func (x *BeginTxResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type CommitTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxToken       string                 `protobuf:"bytes,1,opt,name=tx_token,json=txToken,proto3" json:"tx_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTxRequest) Reset() {
	*x = CommitTxRequest{}
	mi := &file_campus_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTxRequest) ProtoMessage() {}

func (x *CommitTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTxRequest.ProtoReflect.Descriptor instead.
func (*CommitTxRequest) Descriptor() ([]byte, []int) {
	return file_campus_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *CommitTxRequest) GetTxToken() string {
	if x != nil {
		return x.TxToken
	}
	return ""
}

type CommitTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTxResponse) Reset() {
	*x = CommitTxResponse{}
	mi := &file_campus_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTxResponse) ProtoMessage() {}

func (x *CommitTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTxResponse.ProtoReflect.Descriptor instead.
func (*CommitTxResponse) Descriptor() ([]byte, []int) {
	return file_campus_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *CommitTxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RollbackTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxToken       string                 `protobuf:"bytes,1,opt,name=tx_token,json=txToken,proto3" json:"tx_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTxRequest) Reset() {
	*x = RollbackTxRequest{}
	mi := &file_campus_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTxRequest) ProtoMessage() {}

func (x *RollbackTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTxRequest.ProtoReflect.Descriptor instead.
func (*RollbackTxRequest) Descriptor() ([]byte, []int) {
	return file_campus_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *RollbackTxRequest) GetTxToken() string {
	if x != nil {
		return x.TxToken
	}
	return ""
}

type RollbackTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTxResponse) Reset() {
	*x = RollbackTxResponse{}
	mi := &file_campus_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTxResponse) ProtoMessage() {}

func (x *RollbackTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campus_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTxResponse.ProtoReflect.Descriptor instead.
func (*RollbackTxResponse) Descriptor() ([]byte, []int) {
	return file_campus_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *RollbackTxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_campus_v1_common_proto protoreflect.FileDescriptor

const file_campus_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16campus/v1/common.proto\x12\tcampus.v1\"b\n" +
	"\vRequestMeta\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12\x19\n" +
	"\btx_token\x18\x03 \x01(\tR\atxToken\"X\n" +
	"\x0eBeginTxRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"T\n" +
	"\x0fBeginTxResponse\x12\x19\n" +
	"\btx_token\x18\x01 \x01(\tR\atxToken\x12&\n" +
	"\x0fexpires_at_unix\x18\x02 \x01(\x03R\rexpiresAtUnix\",\n" +
	"\x0fCommitTxRequest\x12\x19\n" +
	"\btx_token\x18\x01 \x01(\tR\atxToken\",\n" +
	"\x10CommitTxResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x11RollbackTxRequest\x12\x19\n" +
	"\btx_token\x18\x01 \x01(\tR\atxToken\".\n" +
	"\x12RollbackTxResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe3\x01\n" +
	"\x0fDatabaseService\x12@\n" +
	"\aBeginTx\x12\x19.campus.v1.BeginTxRequest\x1a\x1a.campus.v1.BeginTxResponse\x12C\n" +
	"\bCommitTx\x12\x1a.campus.v1.CommitTxRequest\x1a\x1b.campus.v1.CommitTxResponse\x12I\n" +
	"\n" +
	"RollbackTx\x12\x1c.campus.v1.RollbackTxRequest\x1a\x1d.campus.v1.RollbackTxResponseBSZQgithub.com/Yogesh-Kumar-Mallik-dev/campus-os/backend/pkg/proto/campus/v1;campusv1b\x06proto3"

var (
	file_campus_v1_common_proto_rawDescOnce sync.Once
	file_campus_v1_common_proto_rawDescData []byte
)

func file_campus_v1_common_proto_rawDescGZIP() []byte {
	file_campus_v1_common_proto_rawDescOnce.Do(func() {
		file_campus_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_campus_v1_common_proto_rawDesc), len(file_campus_v1_common_proto_rawDesc)))
	})
	return file_campus_v1_common_proto_rawDescData
}

var file_campus_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_campus_v1_common_proto_goTypes = []any{
	(*RequestMeta)(nil),        // 0: campus.v1.RequestMeta
	(*BeginTxRequest)(nil),     // 1: campus.v1.BeginTxRequest
	(*BeginTxResponse)(nil),    // 2: campus.v1.BeginTxResponse
	(*CommitTxRequest)(nil),    // 3: campus.v1.CommitTxRequest
	(*CommitTxResponse)(nil),   // 4: campus.v1.CommitTxResponse
	(*RollbackTxRequest)(nil),  // 5: campus.v1.RollbackTxRequest
	(*RollbackTxResponse)(nil), // 6: campus.v1.RollbackTxResponse
}
var file_campus_v1_common_proto_depIdxs = []int32{
	1, // 0: campus.v1.DatabaseService.BeginTx:input_type -> campus.v1.BeginTxRequest
	3, // 1: campus.v1.DatabaseService.CommitTx:input_type -> campus.v1.CommitTxRequest
	5, // 2: campus.v1.DatabaseService.RollbackTx:input_type -> campus.v1.RollbackTxRequest
	2, // 3: campus.v1.DatabaseService.BeginTx:output_type -> campus.v1.BeginTxResponse
	4, // 4: campus.v1.DatabaseService.CommitTx:output_type -> campus.v1.CommitTxResponse
	6, // 5: campus.v1.DatabaseService.RollbackTx:output_type -> campus.v1.RollbackTxResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_campus_v1_common_proto_init() }
func file_campus_v1_common_proto_init() {
	if File_campus_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_campus_v1_common_proto_rawDesc), len(file_campus_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_campus_v1_common_proto_goTypes,
		DependencyIndexes: file_campus_v1_common_proto_depIdxs,
		MessageInfos:      file_campus_v1_common_proto_msgTypes,
	}.Build()
	File_campus_v1_common_proto = out.File
	file_campus_v1_common_proto_goTypes = nil
	file_campus_v1_common_proto_depIdxs = nil
}
